In [1]:
from google.colab import files

In [2]:
records = files.upload()

Saving train.csv to train (2).csv


In [3]:
records2 = files.upload()

Saving test.csv to test (2).csv


In [29]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
df = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [31]:
df.head()

Artist Name  ... Class
0             Bruno Mars  ...     5
1                 Boston  ...    10
2          The Raincoats  ...     6
3                   Deno  ...     5
4  Red Hot Chili Peppers  ...    10

[5 rows x 17 columns]

In [32]:
df['Artist Name'].nunique()

9149

In [33]:
most_popular_artiste = df['Artist Name'].value_counts().head(20)
most_popular_artiste

Backstreet Boys       69
Westlife              60
Britney Spears        54
Eyal Golan            48
Omer Adam             48
Shlomo Artzi          39
The Rolling Stones    38
Arik Einstein         35
Itay Levi             35
Dudu Aharon           34
Moshe Peretz          34
Hadag Nahash          33
Yehudit Ravitz        31
U2                    30
Lata Mangeshkar       28
Metallica             27
AC/DC                 27
Dudu Tassa            26
Sarit Hadad           26
The Beatles           25
Name: Artist Name, dtype: int64

In [34]:
top_rated = df[(df['Class'] == 10) | (df['Class'] == 9) | (df['Class'] == 8)]

In [35]:
top_rated.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9327 entries, 1 to 17995
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Artist Name         9327 non-null   object 
 1   Track Name          9327 non-null   object 
 2   Popularity          9145 non-null   float64
 3   danceability        9327 non-null   float64
 4   energy              9327 non-null   float64
 5   key                 8291 non-null   float64
 6   loudness            9327 non-null   float64
 7   mode                9327 non-null   int64  
 8   speechiness         9327 non-null   float64
 9   acousticness        9327 non-null   float64
 10  instrumentalness    6836 non-null   float64
 11  liveness            9327 non-null   float64
 12  valence             9327 non-null   float64
 13  tempo               9327 non-null   float64
 14  duration_in min/ms  9327 non-null   float64
 15  time_signature      9327 non-null   int64  
 16  Class

In [36]:
highly_rated = top_rated['Artist Name'].value_counts().head(20)
highly_rated

Backstreet Boys       69
Westlife              60
Britney Spears        54
Omer Adam             48
Eyal Golan            48
Shlomo Artzi          39
Arik Einstein         35
Itay Levi             35
Dudu Aharon           34
Moshe Peretz          34
The Rolling Stones    32
Yehudit Ravitz        31
Metallica             27
AC/DC                 27
U2                    26
Sarit Hadad           26
Dudu Tassa            25
Shalom Hanoch         24
Berry Sakharof        24
Eliad                 23
Name: Artist Name, dtype: int64

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17996 entries, 0 to 17995
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Artist Name         17996 non-null  object 
 1   Track Name          17996 non-null  object 
 2   Popularity          17568 non-null  float64
 3   danceability        17996 non-null  float64
 4   energy              17996 non-null  float64
 5   key                 15982 non-null  float64
 6   loudness            17996 non-null  float64
 7   mode                17996 non-null  int64  
 8   speechiness         17996 non-null  float64
 9   acousticness        17996 non-null  float64
 10  instrumentalness    13619 non-null  float64
 11  liveness            17996 non-null  float64
 12  valence             17996 non-null  float64
 13  tempo               17996 non-null  float64
 14  duration_in min/ms  17996 non-null  float64
 15  time_signature      17996 non-null  int64  
 16  Clas

In [38]:
X, y = df.drop('Class',axis=1), df['Class']

In [39]:

missing_col = [x for x in X.columns if pd.isnull(X[x]).any()]
missing_col

['Popularity', 'key', 'instrumentalness']

In [40]:
missing_col1 = [x for x in test.columns if pd.isnull(test[x]).any()]
missing_col1

['Popularity', 'key', 'instrumentalness']

In [41]:
for i in missing_col:
  X[i].fillna(X[i].mean(),inplace=True)

In [42]:
for i in missing_col1:
  test[i].fillna(test[i].mean(),inplace=True)

In [43]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()

In [44]:
labels = [x for x in X.columns if X[x].dtypes == object]
labels

['Artist Name', 'Track Name']

In [45]:
label = [x for x in test.columns if test[x].dtypes == object]
label

['Artist Name', 'Track Name']

In [46]:
X[labels] = encoder.fit_transform(X[labels])

In [47]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit_transform(X)

array([[-1.28194609,  0.91186189,  0.89951874, ...,  0.38712996,
         0.30228365,  0.21006549],
       [-1.31589364, -0.5697868 ,  0.55104536, ..., -0.20862857,
         0.45531168,  0.21006549],
       [ 1.25167273,  0.15880206, -0.55245369, ...,  0.84738275,
        -0.81329315,  0.21006549],
       ...,
       [ 0.92464467,  0.30308851, -0.61053259, ..., -0.59597137,
         0.13820959,  0.21006549],
       [-1.42716616,  0.52794451, -0.90092707, ...,  0.29555284,
         0.16920453,  0.21006549],
       [ 1.25129554, -1.31938375, -0.08782251, ...,  0.5234473 ,
        -0.1653551 ,  0.21006549]])

In [48]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X,y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [49]:
test[label] = encoder.fit_transform(test[label])

In [50]:
ss.fit_transform(test)

array([[-1.02174636e+00,  7.65376355e-01,  1.63522246e+00, ...,
         3.87036197e-01,  1.04862649e+00,  2.21636348e-01],
       [-1.09282723e+00, -9.21232450e-01, -6.39814771e-01, ...,
         9.74386414e-01,  1.85570017e-01,  2.21636348e-01],
       [ 4.47030546e-01,  4.31777576e-01,  1.92689390e+00, ...,
        -3.22208951e-02,  3.12589078e-02,  2.21636348e-01],
       ...,
       [ 8.40025761e-01, -3.16357057e-02, -4.06477619e-01, ...,
         4.12068480e-01, -1.76319500e+00,  2.21636348e-01],
       [ 1.08470800e+00, -1.66838735e-01,  3.51868123e-01, ...,
         3.45820409e-01,  1.93589279e-01,  2.21636348e-01],
       [ 1.55188881e-01, -1.04625747e-01,  1.86239578e-03, ...,
         1.11166022e+00,  4.39835951e-03,  2.21636348e-01]])

In [51]:
predictions = classifier.predict_proba(test)
predictions

array([[5.40760986e-04, 5.51771708e-02, 2.70283334e-02, ...,
        5.12213409e-02, 4.23304327e-02, 7.28627324e-01],
       [3.34338692e-04, 6.38896450e-02, 1.60791501e-02, ...,
        5.02823889e-01, 2.10023522e-02, 3.10950577e-01],
       [5.48990909e-04, 8.52602571e-02, 1.09646162e-02, ...,
        7.46958889e-03, 5.20712972e-01, 2.15334520e-01],
       ...,
       [1.59790933e-01, 6.21906808e-03, 1.74906217e-02, ...,
        1.21303480e-02, 4.36579287e-01, 1.30242899e-01],
       [7.97661429e-04, 1.47403866e-01, 7.31769726e-02, ...,
        1.31611563e-02, 1.97139069e-01, 2.39756554e-01],
       [4.59041912e-04, 7.62814879e-02, 5.12475222e-02, ...,
        1.90225132e-02, 1.55308753e-01, 1.12116225e-01]], dtype=float32)

In [52]:
df_output = pd.DataFrame(predictions.round(2),columns=classifier.classes_)

In [53]:
df_output.to_csv('entry2.csv')